name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/Java-with-Maven
          key: ${{runner.os}}-maven-${{hashFiles('**/pom.xml')}}
          restore-keys: |
            ${{runner.os}}-maven-
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Install Dependencies
        run: mvn dependency:resolve
      - name: Run static code analyzer
        run: mvn clean compile spotbugs:check
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify